// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_section_title_ from "./routes/[section]/[title].tsx";
import * as $_section_index from "./routes/[section]/index.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Post from "./islands/Post.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[section]/[title].tsx": $_section_title_,
    "./routes/[section]/index.tsx": $_section_index,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Post.tsx": $Post,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
